.gitlab-ci.yml
bookstack/Dockerfile
bookstack/build.json

⬆ Update Base Image to 3.1.2

---

README.md
bookstack/config.json
bookstack/rootfs/etc/cont-init.d/bookstack.sh
bookstack/rootfs/etc/cont-init.d/mysql.sh
bookstack/rootfs/etc/services.d/mysql/run
bookstack/rootfs/etc/services.d/php-fpm/run

Add external MySQL/MariaDB database config
#1

:sparkles: Add option for external mysql db

---

.gitlab-ci.yml
bookstack/Dockerfile
bookstack/build.json

Update Bookstack to 0.26.3
Update Base Image to 4.0.2

:hammer: Update bookstack and base image

---

LICENSE.md
README.md
bookstack/.README.j2
bookstack/DOCS.md

📚 Update year

---

bookstack/Dockerfile
bookstack/build.json

⬆ Update image to 9.0.1 and package dependencies

---

README.md

📚 Fix commit activity

---

bookstack/Dockerfile

:arrow_up: Upgrades composer to 2.0.9-r0

---

bookstack/Dockerfile
bookstack/build.json

⬆ Update base image to 9.1.2

---

bookstack/Dockerfile

⬆ Update bookstack to v0.31.5

---

bookstack/Dockerfile

:arrow_up: Upgrades php7 to 7.4.15-r0

---

bookstack/Dockerfile

⬆ Update bookstack to v0.31.6

---

bookstack/Dockerfile

⬆ Add php-ldap

---

bookstack/Dockerfile

Upgrades composer to 2.0.11-r0

:arrow_up: Upgrades composer to 2.0.11-r0

---

bookstack/Dockerfile
bookstack/build.json

Upgrades add-on base image to v9.1.5

:arrow_up: Upgrades add-on base image to v9.1.5

---

bookstack/Dockerfile

⬆ Update bookstack to v0.31.7

---

bookstack/rootfs/etc/nginx/includes/server_params.conf

🔨 Remove cache rules

---

bookstack/Dockerfile

⬆ Update Bookstack to v0.31.8

---

bookstack/.README.j2

📚 Fix image link on edge repo

---

bookstack/Dockerfile
bookstack/build.json

⬆️ Upgrades add-on base image to v9.1.7

⬆️ Upgrades add-on base image to v9.1.7

---

bookstack/Dockerfile

⬆ Update mariadb-client to 10.5.9

⬆ Update mariadb-client to 10.5.9

---

bookstack/Dockerfile

⬆ Update bookstack to v21.04.1

⬆ Update bookstack to v21.04.1

---

bookstack/Dockerfile

Upgrades composer to 2.0.13-r0

⬆️ Upgrades composer to 2.0.13-r0

---

bookstack/Dockerfile
bookstack/build.json

Upgrades add-on base image to v9.2.0

⬆️ Upgrades add-on base image to v9.2.0

---

bookstack/DOCS.md

📚 Update docs for removal of APP_URL

📚 Update docs for removal of APP_URL

---

bookstack/Dockerfile

⬆️ Upgrades php7 to 7.4.19-r0

---

bookstack/Dockerfile
bookstack/build.json

Upgrades add-on base image to v9.2.1

⬆️ Upgrades add-on base image to v9.2.1

---

bookstack/Dockerfile
bookstack/build.json

Upgrades add-on base image to v9.2.2

⬆️ Upgrades add-on base image to v9.2.2

---

bookstack/Dockerfile
bookstack/build.json

⬆ Update base image to v10.0.0
⬆ Update php to v7.4.20-r0
⬆ Update nginx to v1.20.1-r3
⬆ Update composer to v2.1.3-r0

⬆ Update base image and dependencies

---

bookstack/Dockerfile

⬆ Update Bookstack to v21.05.2

⬆ Update Bookstack to v21.05.2

---

bookstack/Dockerfile

Upgrades mariadb-client to 10.5.11-r0

⬆️ Upgrades mariadb-client to 10.5.11-r0

---

bookstack/Dockerfile

⬆️ Upgrades php7 to 7.4.21-r0

---

bookstack/Dockerfile

⬆ Update php to 7.4.22-r0

---

bookstack/Dockerfile

⬆ Update Bookstack to v21.05.4

⬆ Update Bookstack to v21.05.4

---

bookstack/Dockerfile

Upgrades mariadb-client to 10.5.12-r0

⬆️ Upgrades mariadb-client to 10.5.12-r0

---

bookstack/Dockerfile

⬆️ Update bookstack to v21.10.2

⬆️ Update bookstack to v21.10.2

---

bookstack/rootfs/etc/cont-init.d/bookstack.sh
bookstack/rootfs/etc/services.d/php-fpm/run

🔨 Fix Laravel Logging as the user cannot write to stderr

🔨 Fix Laravel Logging

---

bookstack/Dockerfile

⬆️ Update Bookstack to v21.10.3

⬆️ Update Bookstack to v21.10.3

---

bookstack/Dockerfile
bookstack/build.json

⬆️ Update base image and dependencies

⬆️ Update base image and dependencies

---

bookstack/Dockerfile

⬆️ Update bookstack to v21.11.1

⬆️ Update bookstack to v21.11.1

---

bookstack/Dockerfile

⬆️ Update bookstack to v21.11.3

⬆️ Update bookstack to v21.11.3

---

bookstack/Dockerfile

⬆️ Update Bookstack to v21.12

---

LICENSE.md
README.md
bookstack/.README.j2
bookstack/DOCS.md

📚 Update Year 🎉

---

README.md
bookstack/.README.j2

🎉 Mark Production Ready

---

bookstack/Dockerfile

⬆️ Update bookstack to v21.12.1

⬆️ Update bookstack to v21.12.1

---

bookstack/Dockerfile

⬆️ Update bookstack to v22.02.2

⬆️ Update bookstack to v22.02.2

---

bookstack/Dockerfile

⬆️ Update bookstack to v22.02.3

⬆️ Update bookstack to v22.02.3

---

bookstack/Dockerfile

⬆️ Update Bookstack to v22.04 and dependencies

⬆️ Update Bookstack to v22.04 and dependencies

---

bookstack/Dockerfile

Adds php-xmlwriter for QR Code generation for OTP setup

🚑 Add php-xmlwriter for QR Code generation

---

bookstack/Dockerfile

⬆️ Update Bookstack to v22.04.1

⬆️ Update Bookstack to v22.04.1

---

bookstack/Dockerfile
bookstack/build.yaml
bookstack/rootfs/etc/cont-init.d/bookstack.sh
bookstack/rootfs/etc/cont-init.d/nginx.sh
bookstack/rootfs/etc/fix-attrs.d/bookstack
bookstack/rootfs/etc/php8/php-fpm.d/www.conf
bookstack/rootfs/etc/services.d/nginx/finish
bookstack/rootfs/etc/services.d/nginx/run
bookstack/rootfs/etc/services.d/php-fpm/finish
bookstack/rootfs/etc/services.d/php-fpm/run

Updates the add-on to the new base image with the upgraded s6 overlay.
All scripts (and php-fpm) have been migrated to work with it.

⬆️ Upgrades add-on base image to 12.0.0

---

bookstack/Dockerfile

⬆️ Update Bookstack to v22.04.2

⬆️ Update Bookstack to v22.04.2

---

bookstack/Dockerfile
bookstack/build.yaml

⬆️ Upgrades add-on base image to 12.2.2

---

bookstack/Dockerfile

Reduces add-on image size by about ~16Mb by cleaning up the composer cache folder.
Needs #190

Reduce add-on image size

---

bookstack/Dockerfile

⬆️ Update Bookstack to v22.07.1

⬆️ Update Bookstack to v22.07.1

---

bookstack/Dockerfile

⬆️Update Bookstack to v22.10.1 and dependencies

⬆️Update Bookstack to v22.10.1 and dependencies

---

bookstack/Dockerfile
bookstack/build.yaml

⬆️ Update image and dependencies

⬆️ Update image and dependencies

---

bookstack/Dockerfile

⬆️ Update Bookstack to v22.10.2

⬆️ Update Bookstack to v22.10.2

---

bookstack/Dockerfile

⬆️ Update php to 8.0.26-r0

---

bookstack/Dockerfile

⬆️ Update Bookstack to v22.11

---

bookstack/rootfs/etc/cont-init.d/bookstack.sh

Update php path to fix appkey generation on fresh install
Fixes #205

🚑 Fix appkey generation for new installs

---

bookstack/Dockerfile

⬆️ Update Bookstack to v23.02.1

⬆️ Update Bookstack to v23.02.1

---

.github/dependabot.yaml
.github/renovate.json
bookstack/Dockerfile

Add Renovate for dependency management

---

.github/renovate.json

A honest typo that sneaked in. Sorry about that.
../Frenck

Fix Renovate repology template

---

bookstack/Dockerfile

Add php-iconv to resolve issue for 2FA setup
Fixes #248

🚑 Add php-iconv for 2FA setup

---

README.md
bookstack/build.yaml
bookstack/config.yaml

Drop support for armhf & i386

---

LICENSE.md
README.md
bookstack/.README.j2
bookstack/DOCS.md

📚 Update year to 2024
